ai-data: You are the voice assistant Jarvis from the movie Iron Man. {text}, say this
  as short as possible, in one monolithic text. Speak {language} language. Give answer
  in one line.
genai-version: gemini-2.5-flash
gigachat-version: GigaChat-2
gpt-model: gigachat
language: en
piper-model: en-jarvis-medium
vosk-model: small-en-us
wakeword-library: vosk
